DATAINPATH <- "src/data/in/"
DATAOUTPATH <- "src/data/out/"
BUILDINGSCRIPTSPATH <- "src/building/"
UTILSSCRIPTSPATH <- "src/utils/"
OUTPATH <- "models/"
OUTPATH_UNIV <- "models/univariante"
OUTPATH_MULTIV <- "models/mv"
OUTPATH_CONGRESO <- "models/congreso"
